live_config_reload = true

[colors.bright]
black = "#928374"
blue = "#458588"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#b16287"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.dim]
black = "#282828"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#d5c4a1"
yellow = "#b57614"

[colors.normal]
black = "#282828"
blue = "#83a598"
cyan = "#689d6a"
green = "#98971a"
magenta = "#d3869b"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[window]
padding = { x = 10, y = 15 }
decorations = "buttonless"
opacity = 0.85

